// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function GetHandler() {
  return window['go']['main']['App']['GetHandler']();
}

export function GetRoutes() {
  return window['go']['main']['App']['GetRoutes']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}
