// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {main} from '../models';

export function GetCurrentDirectory():Promise<string>;

export function GetHandler():Promise<http.Handler>;

export function GetRoutes():Promise<Array<main.RouteInfo>>;

export function GetServerURL():Promise<string>;

export function OpenDirectory():Promise<string>;

export function OpenFile():Promise<string>;
